import type { Metadata } from "next";
import Cabecalho from "./Components/Cabecalho/Cabecalho";
import Conteudo from "./Components/Conteudo/Conteudo";
import Rodape from "./Components/Rodape/Rodape";

export const metadata: Metadata = {
  title: "Help Car",
  description: "Generated by create next app",
};

export const viewport = {
  colorScheme:'dark'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Cabecalho/>
        <Conteudo/>
        {children}
        <Rodape/>
      </body>
    </html>
  );
}
