import type { Metadata } from "next";
import Cabecalho from "./Components/Cabecalho/Cabecalho";
import Rodape from "./Components/Rodape/Rodape";


export const metadata: Metadata = {
  title: "Help Car",
  description: "Generated by create next app",
};

export const viewport = {
  colorScheme:'dark'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className="w-[100%] h-[100%]">
        <Cabecalho/>
        {children}
        <Rodape/>
      </body>
    </html>
  );
}
